version: '2'
services:
  ssh_machine:
    image: 'dockersecplayground/alpine_ssh_password:latest'
    stdin_open: true
    tty: true
    ports:
      - '2200:22'
    networks:
      external_subnet:
        ipv4_address: 193.20.2.3
    cap_add:
      - NET_ADMIN
  router:
    image: 'dockersecplayground/alpine_router:latest'
    stdin_open: true
    tty: true
    networks:
      internal_subnet:
        ipv4_address: 193.20.1.2
      external_subnet:
        ipv4_address: 193.20.2.2
    cap_add:
      - NET_ADMIN
  website:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:80'
    networks:
      internal_subnet:
        ipv4_address: 193.20.1.3
    volumes:
      - './website:/var/www/example.com/public_html'
    cap_add:
      - NET_ADMIN
networks:
  internal_subnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
  external_subnet:
    ipam:
      config:
        - subnet: 193.20.2.1/24
