version: '2'
services:
  router:
    image: 'dockersecplayground/alpine_router:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.2
      telnet_network:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
  TelnetServer:
    image: 'dockersecplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      telnet_network:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
  telnet_client:
    image: 'dockersecplayground/alpine_bot:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.2.4
    cap_add:
      - NET_ADMIN
  Kali:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:4200'
    networks:
      internal_network:
        ipv4_address: 192.168.2.3
    volumes:
      - './dump_sniff:/dump_sniff'
    cap_add:
      - ALL
networks:
  telnet_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  internal_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
