version: '2'
services:
  TelnetServer:
    image: 'dockersecplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      telnet_subnet:
        ipv4_address: 193.20.1.3
    cap_add:
      - NET_ADMIN
  router:
    image: 'dockersecplayground/alpine_router:latest'
    stdin_open: true
    tty: true
    networks:
      telnet_subnet:
        ipv4_address: 193.20.1.2
      internal_subnet:
        ipv4_address: 193.20.2.2
    cap_add:
      - NET_ADMIN
  telnet_client:
    image: 'dockersecplayground/alpine_bot:latest'
    stdin_open: true
    tty: true
    networks:
      internal_subnet:
        ipv4_address: 193.20.2.4
    cap_add:
      - NET_ADMIN
  entry_point:
    image: 'dockersecplayground/alpine_pentest:latest'
    stdin_open: true
    tty: true
    ports:
      - '22000:22'
    networks:
      internal_subnet:
        ipv4_address: 193.20.2.3
    cap_add:
      - ALL
networks:
  telnet_subnet:
    ipam:
      config:
        - subnet: 193.20.1.1/24
  internal_subnet:
    ipam:
      config:
        - subnet: 193.20.2.1/24
