version: '2'
services:
  WebServer:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '11110:80'
    volumes:
      - './website:/var/www/example.com/public_html/DVWA'
    cap_add:
      - NET_ADMIN
networks: {}
