version: '2'
services:
  website:
    image: 'dockersecplayground/linode_lamp:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:80'
    networks:
      internal_network:
        ipv4_address: 192.168.1.3
    volumes:
      - './website:/var/www/example.com/public_html'
    cap_add:
      - NET_ADMIN
  router:
    image: 'dockersecplayground/alpine_router:latest'
    stdin_open: true
    tty: true
    networks:
      internal_network:
        ipv4_address: 192.168.1.2
      external_network:
        ipv4_address: 192.168.2.2
    cap_add:
      - NET_ADMIN
  kali:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '11000:4200'
    networks:
      external_network:
        ipv4_address: 192.168.2.3
    volumes:
      - './history:/history'
    cap_add:
      - ALL
networks:
  internal_network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
  external_network:
    ipam:
      config:
        - subnet: 192.168.2.1/24
