version: '2'
services:
  SSH_SERVER_PASSWORD:
    image: 'dockersecplayground/alpine_ssh_password:latest'
    stdin_open: true
    tty: true
    ports:
      - '13000:22'
    cap_add:
      - NET_ADMIN
  EntryPoint:
    image: 'dockersecplayground/kali:latest'
    stdin_open: true
    tty: true
    ports:
      - '10000:4200'
    cap_add:
      - ALL
  SSH_SERVER_KEYS:
    image: 'dockersecplayground/ssh_keys:latest'
    stdin_open: true
    tty: true
    ports:
      - '12000:22'
    environment:
      - >-
        AUTHORIZED_KEYS=ssh-rsa
        AAAAB3NzaC1yc2EAAAADAQABAAABAQDoKOaUNFQoopOjyoR3oNzrHHnHXnmbzStgus7cwZN6BHG6VdM5Y2arKaVCmvzpp0RrMCrN7KgSc0QKd8VoyB7plDFiJfkCQDs9/2AjGGThVXOoSm+ylxotDYbPHemFfBuwpHNmSU7St0x27dQ1n5IDyliPM6zlysK5mTNLZfLN7xTaBJag6mdUC82cj6MPl1D59a4Wl6rPVcfX5tHKuLWDQ4ulzQdHRGV4Rgu6Qp2Pu9vlNuGtUHqKhZ5Rq6D3s7pmDGWEJMZ6E8ZwOea5MNJVrH6813+CeQxPu3MBDiz16kkZg1sIr3Npdzck8hY9QeUrzzKWW0iL0IIZ591+oc+V
    cap_add:
      - NET_ADMIN
networks: {}
