version: '2'
services:
  ts:
    image: 'dockersecplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
  tc:
    image: 'dockersecplayground/alpine_bot:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
networks:
  network:
    ipam:
      config:
        - subnet: 192.168.1.1/24
