version: '2'
services:
  ftpServer:
    image: 'dockersecplayground/alpine_ftp:latest'
    stdin_open: true
    tty: true
    networks:
      subnet:
        ipv4_address: 192.168.1.2
    cap_add:
      - NET_ADMIN
  telnet_server:
    image: 'dockersecplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      subnet:
        ipv4_address: 192.168.1.3
    cap_add:
      - NET_ADMIN
networks:
  subnet:
    ipam:
      config:
        - subnet: 192.168.1.1/24
