version: '2'
services:
  ftpServer:
    image: 'dockersecplayground/alpine_ftp:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 193.20.1.2
    cap_add:
      - NET_ADMIN
  telnet_server:
    image: 'dockersecplayground/alpine_telnet:latest'
    stdin_open: true
    tty: true
    networks:
      network:
        ipv4_address: 193.20.1.3
    cap_add:
      - NET_ADMIN
networks:
  network:
    ipam:
      config:
        - subnet: 193.20.1.1/24
